"""
ProposalGeneration Model
Tracks each AI-generated proposal
"""

from sqlalchemy import Column, String, Text, DateTime, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

from app.db.base import BaseModel


class ProposalGeneration(BaseModel):
    """
    Tracks each proposal generated by the AI.
    Stores the proposal content and metadata for later feedback/regeneration.
    """
    __tablename__ = "proposal_generations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id = Column(UUID(as_uuid=True), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False)
    created_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)

    # Proposal metadata
    proposal_title = Column(String, nullable=False)  # "RFP Response - XYZ Corp"
    proposal_type = Column(String, nullable=False)  # "service", "product", "bid", "general"

    # Content (store full proposal for reference/regeneration)
    proposal_content = Column(Text, nullable=True)  # Full proposal text/HTML
    proposal_metadata = Column(JSONB, nullable=True)  # {sections: {...}, pricing: {...}, timeline: {...}}

    # AI settings used (snapshot of preferences at generation time)
    writing_preferences = Column(JSONB, nullable=True)  # Snapshot of ProposalPreferences used

    # Status and regeneration tracking
    status = Column(String, default="draft")  # "draft", "finalized", "regenerated"
    parent_proposal_id = Column(UUID(as_uuid=True), ForeignKey("proposal_generations.id", ondelete="SET NULL"), nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    regenerated_at = Column(DateTime, nullable=True)

    # Relationships
    organization = relationship("Organization")
    created_by_user = relationship("User")
    feedback = relationship(
        "ProposalFeedback",
        back_populates="proposal",
        foreign_keys="ProposalFeedback.proposal_id"
    )
    parent_proposal = relationship("ProposalGeneration", remote_side=[id], backref="regenerations")

    # Indexes
    __table_args__ = (
        Index('idx_org_proposals', 'organization_id', 'created_at'),
        Index('idx_parent_proposal', 'parent_proposal_id'),
        Index('idx_created_by', 'created_by'),
    )

    def to_dict(self):
        """Convert to dictionary for API response"""
        return {
            "id": str(self.id),
            "organization_id": str(self.organization_id),
            "created_by": str(self.created_by),
            "proposal_title": self.proposal_title,
            "proposal_type": self.proposal_type,
            "status": self.status,
            "parent_proposal_id": str(self.parent_proposal_id) if self.parent_proposal_id else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "regenerated_at": self.regenerated_at.isoformat() if self.regenerated_at else None,
            "feedback_count": len(self.feedback) if self.feedback else 0,
        }

    def to_dict_full(self):
        """Convert to dictionary with full content for API response"""
        data = self.to_dict()
        data["proposal_content"] = self.proposal_content
        data["proposal_metadata"] = self.proposal_metadata
        data["writing_preferences"] = self.writing_preferences
        return data
